server {
    listen 80;
    listen 443 ssl;
    server_name tipsterpage.test;

    ssl_certificate /etc/nginx/certs/apache.crt; # Usaremos certificados genéricos para dev
    ssl_certificate_key /etc/nginx/certs/apache.key;

    location / {
        proxy_pass http://landing_laravel:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    listen 443 ssl;
    server_name affiliabet.test;

    ssl_certificate /etc/nginx/certs/apache.crt;
    ssl_certificate_key /etc/nginx/certs/apache.key;

    location / {
        proxy_pass http://affiliabet_laravel:80;
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    listen 443 ssl;
    server_name apibagon.test;

    ssl_certificate /etc/nginx/certs/apache.crt;
    ssl_certificate_key /etc/nginx/certs/apache.key;

    location / {
        proxy_pass http://apibagon_laravel:80;
        proxy_set_header Host $host;
    }
}